### PR TITLE
Fix version sorting for building plugin cache data. Fixes #2043

### LINKED ISSUE #2043: Plugin Manager - False "Last version"
There is a sort of problem in the version numbers. Sometimes the proposed version is not the latest version.

Exemple with TernJs.

Last version in LightTable : 0.1.9
Real last version : 0.1.10

Metadata repository is correct.

### PR DESCRIPTION
**Pull request by kenny-evitt**
Previously `build-cache` was attempting to sort plugin versions but [`sort-by`](https://clojuredocs.org/clojure.core/sort-by) was being called with the version comparator being passed as the sort key function. The version comparator was also inverting the standard return values for a comparator – see [`compare`](https://clojuredocs.org/clojure.core/compare) for an example.

### CODE REVIEW

**Comment by kenny-evitt** [comment]
@cldwalker @rundis This seems pretty minor but it would be nice to include in the next release.

File: src/lt/objs/plugins.cljs [hunk 1]
```diff
@@ -207,7 +207,7 @@
                           :let [versions (->> (files/full-path-ls plugin)
                                               (filter files/dir?)
                                               (map plugin-info)
-                                              (sort-by #(version-sort % %2))
+                                              (sort-by #(:version %) version-sort)
```
Comment (cldwalker) [inline src/lt/objs/plugins.cljs]: `#(:version %)` can just be :version

**Comment by cldwalker** [comment]
@kenny-evitt Nice sleuthing and thanks for digging into this! I'm surprised sort was ever working without :version. Feel free to merge after that minor suggestion

File: src/lt/objs/plugins.cljs (hunk 1 above)
Comment (kenny-evitt) [inline src/lt/objs/plugins.cljs]: Good point

**Comment by kenny-evitt** [comment]
@cldwalker This seems to have worked because the directory enumeration must have been effectively ordering the directories by name.
